In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import linregress

file_worldwide = "../Kasy-Resources/worldwide-sbux-locations.csv"
file_mcd = "../Kasy-Resources/mcdonalds_locations.csv"
sbux_nutrition = "../Kasy-Resources/starbucks-menu-nutrition-drinks.csv"
mcd_nutrition = "../Kasy-Resources/mcd_nutrition.csv"
subway_nutrition = "../Kasy-Resources/subway_nutrition.csv"
city_population = "./uscitypopdensity.csv"

sbux_df = pd.read_csv(file_worldwide)
sbux_nutrition_df = pd.read_csv(sbux_nutrition)
mcd_nutrition_df = pd.read_csv(mcd_nutrition)
subway_nutrition_df = pd.read_csv(subway_nutrition)
city_population = pd.read_csv(city_population)

In [5]:
city_population.reset_index()


##TO DO - remove double index

,index,Index,City,State,Population Density (Persons/Square Mile),2016 Population,Land Area (Square Miles)
0,0,1,New York,New York,28211,8537673,303
1,1,2,Los Angeles,California,8484,3976322,469
2,2,3,Chicago,Illinois,11883,2704958,228
3,3,4,Houston,Texas,3842,2303482,600
4,4,5,Phoenix,Arizona,3126,1615017,517
...,...,...,...,...,...,...,...
749,749,750,Cerritos,California,5791,50555,9
750,750,751,Galveston,Texas,1226,50550,41
751,751,752,Coeur d'Alene,Idaho,3230,50285,16
752,752,753,Lakewood,Ohio,9092,50279,6
753,753,754,Poway,California,1281,50077,39

In [4]:
renamed_subway_df = subway_nutrition_df.rename(columns={"Unnamed: 0": "Subway Item"})
renamed_subway_df

,Subway Item,Category,Serving Size (g),Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbohydrates (g),Dietary Fiber (g),Sugars (g),Protein (g),Vitamin A % DV,Vitamin C % DV,Calcium % DV,Iron % DV
0,BBQ Rib,Sandwich,208,580,31.0,10.0,0.0,60,1260,54,3,18,21,8,4,4,20
1,Black Forest Ham,Sandwich,219,260,4.0,1.5,0.0,30,720,42,5,8,18,30,15,4,15
2,Chicken & Bacon Ranch Melt,Sandwich,284,530,26.0,10.0,0.5,100,1100,41,3,6,36,40,25,20,20
3,Chicken Mango Curry,Sandwich,234,330,7.0,1.5,0.0,50,840,43,3,9,24,15,20,2,25
4,Chicken Tikka,Sandwich,205,290,5.0,1.0,0.0,50,720,39,2,6,23,10,10,0,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,Red Onions,Veggies,7,0,0.0,0.0,0.0,0,0,1,0,0,0,0,0,0,0
131,Spinach,Veggies,7,0,0.0,0.0,0.0,0,5,0,0,0,0,15,2,0,0
132,Tomatoes,Veggies,35,5,0.0,0.0,0.0,0,0,1,0,1,0,10,4,0,0
133,Bacon,Protein,15,70,6.0,2.0,0.0,15,250,1,0,1,5,0,6,0,0
134,Parmesan Cheese,Seasonings,1,5,0.0,0.0,0.0,0,25,0,0,0,1,0,0,0,0

In [5]:
max_mcd_cal = mcd_nutrition_df["Calories"].max()
min_mcd_cal = mcd_nutrition_df["Calories"].min()
mcd_nutrition_df["Category"].unique()
mcd_nutrition_df

,Category,Item,Serving Size,Calories,Calories from Fat,Total Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
0,Breakfast,Egg McMuffin,4.8 oz (136 g),300,120,13.0,20,5.0,25,0.0,...,31,10,4,17,3,17,10,0,25,15
1,Breakfast,Egg White Delight,4.8 oz (135 g),250,70,8.0,12,3.0,15,0.0,...,30,10,4,17,3,18,6,0,25,8
2,Breakfast,Sausage McMuffin,3.9 oz (111 g),370,200,23.0,35,8.0,42,0.0,...,29,10,4,17,2,14,8,0,25,10
3,Breakfast,Sausage McMuffin with Egg,5.7 oz (161 g),450,250,28.0,43,10.0,52,0.0,...,30,10,4,17,2,21,15,0,30,15
4,Breakfast,Sausage McMuffin with Egg Whites,5.7 oz (161 g),400,210,23.0,35,8.0,42,0.0,...,30,10,4,17,2,21,6,0,25,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Smoothies & Shakes,McFlurry with Oreo Cookies (Small),10.1 oz (285 g),510,150,17.0,26,9.0,44,0.5,...,80,27,1,4,64,12,15,0,40,8
256,Smoothies & Shakes,McFlurry with Oreo Cookies (Medium),13.4 oz (381 g),690,200,23.0,35,12.0,58,1.0,...,106,35,1,5,85,15,20,0,50,10
257,Smoothies & Shakes,McFlurry with Oreo Cookies (Snack),6.7 oz (190 g),340,100,11.0,17,6.0,29,0.0,...,53,18,1,2,43,8,10,0,25,6
258,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Medium),14.2 oz (403 g),810,290,32.0,50,15.0,76,1.0,...,114,38,2,9,103,21,20,0,60,6
259,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Snack),7.1 oz (202 g),410,150,16.0,25,8.0,38,0.0,...,57,19,1,5,51,10,10,0,30,4

In [59]:
mcd_beverages = mcd_nutrition_df.loc[(mcd_nutrition_df["Category"] == "Beverages") | 
                                     (mcd_nutrition_df["Category"] == "Coffee & Tea") |
                                     (mcd_nutrition_df["Category"] == "Smoothies & Shakes")]
mcd_beverages

,Category,Item,Serving Size,Calories,Calories from Fat,Total Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
110,Beverages,Coca-Cola Classic (Small),16 fl oz cup,140,0,0.0,0,0.0,0,0.0,...,39,13,0,0,39,0,0,0,0,0
111,Beverages,Coca-Cola Classic (Medium),21 fl oz cup,200,0,0.0,0,0.0,0,0.0,...,55,18,0,0,55,0,0,0,0,0
112,Beverages,Coca-Cola Classic (Large),30 fl oz cup,280,0,0.0,0,0.0,0,0.0,...,76,25,0,0,76,0,0,0,0,0
113,Beverages,Coca-Cola Classic (Child),12 fl oz cup,100,0,0.0,0,0.0,0,0.0,...,28,9,0,0,28,0,0,0,0,0
114,Beverages,Diet Coke (Small),16 fl oz cup,0,0,0.0,0,0.0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,Smoothies & Shakes,McFlurry with Oreo Cookies (Small),10.1 oz (285 g),510,150,17.0,26,9.0,44,0.5,...,80,27,1,4,64,12,15,0,40,8
256,Smoothies & Shakes,McFlurry with Oreo Cookies (Medium),13.4 oz (381 g),690,200,23.0,35,12.0,58,1.0,...,106,35,1,5,85,15,20,0,50,10
257,Smoothies & Shakes,McFlurry with Oreo Cookies (Snack),6.7 oz (190 g),340,100,11.0,17,6.0,29,0.0,...,53,18,1,2,43,8,10,0,25,6
258,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Medium),14.2 oz (403 g),810,290,32.0,50,15.0,76,1.0,...,114,38,2,9,103,21,20,0,60,6
259,Smoothies & Shakes,McFlurry with Reese's Peanut Butter Cups (Snack),7.1 oz (202 g),410,150,16.0,25,8.0,38,0.0,...,57,19,1,5,51,10,10,0,30,4

In [6]:
renamed_subway_df.describe()

,Serving Size (g),Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbohydrates (g),Dietary Fiber (g),Sugars (g),Protein (g),Vitamin A % DV,Vitamin C % DV,Calcium % DV,Iron % DV
count,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000,135.000000
mean,178.296296,289.962963,12.818519,4.448148,0.111111,41.777778,739.814815,29.577778,2.570370,5.600000,15.525926,19.888889,14.555556,6.037037,13.370370
std,163.070861,260.549431,14.557094,5.280658,0.338272,51.948836,741.332354,24.881650,2.293862,6.075643,16.625744,24.808721,18.539054,7.801079,11.193509
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28.000000,80.000000,3.250000,0.750000,0.000000,0.000000,130.000000,4.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000
50%,162.000000,220.000000,8.000000,2.500000,0.000000,20.000000,520.000000,30.000000,2.000000,4.000000,9.000000,10.000000,6.000000,4.000000,15.000000
75%,312.500000,440.000000,16.500000,6.000000,0.000000,60.000000,1140.000000,42.500000,4.000000,7.000000,24.000000,30.000000,25.000000,10.000000,20.000000
max,773.000000,1590.000000,78.000000,30.000000,2.000000,335.000000,3930.000000,114.000000,11.000000,32.000000,118.000000,110.000000,90.000000,50.000000,50.000000

In [ ]:
#create calorie bins

#

In [7]:
mcd_nutrition_df.describe()

,Calories,Calories from Fat,Total Fat,Total Fat (% Daily Value),Saturated Fat,Saturated Fat (% Daily Value),Trans Fat,Cholesterol,Cholesterol (% Daily Value),Sodium,...,Carbohydrates,Carbohydrates (% Daily Value),Dietary Fiber,Dietary Fiber (% Daily Value),Sugars,Protein,Vitamin A (% Daily Value),Vitamin C (% Daily Value),Calcium (% Daily Value),Iron (% Daily Value)
count,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,...,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000,260.000000
mean,368.269231,127.096154,14.165385,21.815385,6.007692,29.965385,0.203846,54.942308,18.392308,495.750000,...,47.346154,15.780769,1.630769,6.530769,29.423077,13.338462,13.426923,8.534615,20.973077,7.734615
std,240.269886,127.875914,14.205998,21.885199,5.321873,26.639209,0.429133,87.269257,29.091653,577.026323,...,28.252232,9.419544,1.567717,6.307057,28.679797,11.426146,24.366381,26.345542,17.019953,8.723263
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,210.000000,20.000000,2.375000,3.750000,1.000000,4.750000,0.000000,5.000000,2.000000,107.500000,...,30.000000,10.000000,0.000000,0.000000,5.750000,4.000000,2.000000,0.000000,6.000000,0.000000
50%,340.000000,100.000000,11.000000,17.000000,5.000000,24.000000,0.000000,35.000000,11.000000,190.000000,...,44.000000,15.000000,1.000000,5.000000,17.500000,12.000000,8.000000,0.000000,20.000000,4.000000
75%,500.000000,200.000000,22.250000,35.000000,10.000000,48.000000,0.000000,65.000000,21.250000,865.000000,...,60.000000,20.000000,3.000000,10.000000,48.000000,19.000000,15.000000,4.000000,30.000000,15.000000
max,1880.000000,1060.000000,118.000000,182.000000,20.000000,102.000000,2.500000,575.000000,192.000000,3600.000000,...,141.000000,47.000000,7.000000,28.000000,128.000000,87.000000,170.000000,240.000000,70.000000,40.000000

In [ ]:
# # Household incomes 

# ca_income = income_df.loc[income_df["State_Name"] == "California"]
# ca_income = ca_income[["State_Name", "City", "Mean", "Median", "Stdev"]]
# ca_income = ca_income.rename({"State_Name": "State"}).reset_index()
# ca_income = ca_income.drop(columns="index")
# median = ca_income.groupby("City").median()["Median"]
# mean = ca_income.groupby("City").mean()["Mean"]

# ca_income_cleaned = {"Mean": mean, 
#                     "Median": median}
# ca_income_cleaned_df = pd.DataFrame(ca_income_cleaned)
# ca_income_cleaned_df

In [ ]:
# test = ca_income_cleaned_df.groupby(["City"]).mean().reset_index()
# test
# # ca_income_cleaned_df.sort_values(by="Median", ascending=False).head(50)
# test.loc[test["City"] == "San diego"]

In [ ]:
us_sbux = worldwide_sbux[worldwide_sbux["Country"] == "US"]
ca_sbux["City"] = ca_sbux["City"].str.capitalize()
ca_sbux = ca_sbux.replace("Ahaheim", "Anaheim")
ca_sbux = ca_sbux.replace("Ahaheim hills", "Anaheim")
ca_sbux = ca_sbux.replace("Gold river", "Goleta")
ca_sbux = ca_sbux.replace("San francisco intl a", "San francisco")
ca_sbux = ca_sbux.replace("Sandiego", "San diego")
ca_sbux = ca_sbux.replace("South corona", "Corona")
ca_sbux = ca_sbux.replace("South san francisco", "San francisco")
ca_sbux = ca_sbux.replace("Stanford", "Palo alto")
ca_sbux = ca_sbux.replace("Travis afb", "Fairfield")
ca_sbux = ca_sbux.replace("West hollywood", "Los angeles")
ca_sbux = ca_sbux.replace("Westlake", "Westlake village")
ca_sbux = ca_sbux.replace("Westwood", "Los angeles")
ca_sbux = ca_sbux[["City", "State/Province", "Country"]]
ca_sbux_cleaned = ca_sbux.groupby(["City"]).count().reset_index()
ca_sbux_cleaned.sort_values(by="State/Province")

In [ ]:
# merged_df = pd.merge(ca_sbux_cleaned, ca_income_cleaned_df, on="City", how="inner")
# merged_df = merged_df[["Country", "Mean", "Median"]]
# merged_df_cleaned = merged_df.rename(columns={"Country":"Starbuck Stores", 
#                                      "Mean":"Mean Income", 
#                                      "Median":"Median Income"})
# merged_df_cleaned

In [ ]:
# x_axis = merged_df_cleaned["Starbuck Stores"]
# y_axis = merged_df_cleaned["Median Income"]
# plt.scatter(x_axis, y_axis, marker="o", facecolors="blue", alpha=0.5)
# (slope, intercept, rvalue, pvalue, stderr) = linregress(x_axis, y_axis)
# regress_values = x_axis * slope + intercept
# line_eq = "y = " + str(round(slope,2)) + "x + " + str(round(intercept,2))
# plt.plot(x_axis,regress_values,"r-")
# plt.title("Number of starbuck Stores vs. Median Income")
# plt.xlabel("Number of Starbuck Stores")
# plt.ylabel("Median Income")
# plt.annotate(line_eq,(20,100000),fontsize=15,color="red")

In [ ]:
# x_axis = merged_df_cleaned["Starbuck Stores"]
# y_axis = merged_df_cleaned["Median Income"]
# plt.scatter(y_axis, x_axis, marker="o", facecolors="blue", alpha=0.5)
# (slope, intercept, rvalue, pvalue, stderr) = linregress(y_axis, x_axis)
# regress_values = y_axis * slope + intercept
# line_eq = "y = " + str(round(slope,2)) + "x + " + str(round(intercept,2))
# plt.plot(y_axis,regress_values,"r-")
# plt.title("Number of starbuck Stores vs. Median Income")
# plt.ylabel("Number of Starbuck Stores")
# plt.xlabel("Median Income")
# plt.annotate(line_eq,(50000, 40),fontsize=15,color="red")
# print(rvalue)